version: "3"

volumes:
        produtosdata:

networks:
        frontend:
        backend:        

services:

        mysql:
          image: "mysql:5.7"
          volumes:
            - produtosdata:/var/lib/mysql
            - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
          networks:
            - backend
          environment:
            - MYSQL_ROOT_PASSWORD=linuxens
            - bind-address=0.0.0.0