FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN mkdir /app
WORKDIR /app
COPY docker-essentials.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o dist
EXPOSE 80/tcp
CMD ["dotnet", "dist/docker-essentials.dll"]